# Generated by Django 5.2.7 on 2025-10-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_nofication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nofication',
            new_name='Notification',
        ),
    ]
