# Generated by Django 5.2.7 on 2025-10-08 14:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent_offsets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='List of days before due date for which reminders have already been sent', size=None),
        ),
    ]
