# Generated by Django 5.2.7 on 2025-10-09 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='tasks_collaborating', to=settings.AUTH_USER_MODEL),
        ),
    ]
